version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: telegram_bot
    env_file:
      - bot/config_data/.env
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq/
    depends_on:
      - rabbitmq

  neiro:
    build:
      context: .
      dockerfile: neiro/Dockerfile
    container_name: neiro_module
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq/
    depends_on:
      - rabbitmq
