[tool.poetry]
name = "webapp"
version = "0.1.0"
description = ""
authors = ["Nemyata <Sidorov.2001.Pavel@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.111.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
