name: Deploy to Server

on:
  push:
    branches:
      - SmileAI-usr-bot  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t your_dockerhub_username/smileaibot:latest .
        docker push your_dockerhub_username/smileaibot:latest

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          docker pull your_dockerhub_username/smileaibot:latest
          docker stop smileaibot || true
          docker rm smileaibot || true
          docker run -d --name smileaibot -p 4000:80 your_dockerhub_username/smileaibot:latest